export const categories = [
  {
    id: 'essencial',
    label: 'Essencial',
    emoji: '⭐',
    color: '#DC2626',
    buttons: [
      { label: 'Sim', emoji: '✅', phrase: 'Sim' },
      { label: 'Não', emoji: '❌', phrase: 'Não' },
      { label: 'Talvez', emoji: '🤔', phrase: 'Talvez' },
      { label: 'Ajuda', emoji: '🆘', phrase: 'Preciso de ajuda' },
      { label: 'Dor', emoji: '😣', phrase: 'Estou com dor' },
      { label: 'Obrigado', emoji: '🙏', phrase: 'Muito obrigado' },
    ],
  },
  {
    id: 'necessidades',
    label: 'Necessidades',
    emoji: '💧',
    color: '#2563EB',
    buttons: [
      { label: 'Água', emoji: '💧', phrase: 'Preciso de água' },
      { label: 'Banheiro', emoji: '🚽', phrase: 'Preciso ir ao banheiro' },
      { label: 'Comida', emoji: '🍽️', phrase: 'Estou com fome' },
      { label: 'Remédio', emoji: '💊', phrase: 'Preciso do meu remédio' },
      { label: 'Descansar', emoji: '😴', phrase: 'Quero descansar' },
      { label: 'Frio', emoji: '🥶', phrase: 'Estou com frio' },
      { label: 'Calor', emoji: '🥵', phrase: 'Estou com calor' },
      { label: 'Luz', emoji: '💡', phrase: 'Pode acender a luz' },
    ],
  },
  {
    id: 'dor',
    label: 'Dor',
    emoji: '🤕',
    color: '#9333EA',
    buttons: [
      { label: 'Sem dor', emoji: '😌', phrase: 'Não estou com dor' },
      { label: 'Pouca dor', emoji: '😕', phrase: 'Estou com um pouco de dor' },
      { label: 'Muita dor', emoji: '😭', phrase: 'Estou com muita dor' },
      { label: 'Cabeça', emoji: '🤯', phrase: 'Minha cabeça está doendo' },
      { label: 'Peito', emoji: '💔', phrase: 'Estou com dor no peito' },
      { label: 'Barriga', emoji: '🤢', phrase: 'Minha barriga está doendo' },
      { label: 'Costas', emoji: '🔙', phrase: 'Minhas costas estão doendo' },
      { label: 'Perna', emoji: '🦵', phrase: 'Minha perna está doendo' },
    ],
  },
  {
    id: 'sentimentos',
    label: 'Sentimentos',
    emoji: '😊',
    color: '#059669',
    buttons: [
      { label: 'Bem', emoji: '😊', phrase: 'Estou me sentindo bem' },
      { label: 'Mal', emoji: '😔', phrase: 'Não estou me sentindo bem' },
      { label: 'Cansado', emoji: '😩', phrase: 'Estou muito cansado' },
      { label: 'Com medo', emoji: '😨', phrase: 'Estou com medo' },
      { label: 'Feliz', emoji: '😄', phrase: 'Estou feliz' },
      { label: 'Triste', emoji: '😢', phrase: 'Estou triste' },
      { label: 'Ansioso', emoji: '😰', phrase: 'Estou ansioso' },
      { label: 'Calmo', emoji: '😌', phrase: 'Estou calmo' },
    ],
  },
  {
    id: 'pessoas',
    label: 'Pessoas',
    emoji: '👥',
    color: '#D97706',
    buttons: [
      { label: 'Médico', emoji: '👨‍⚕️', phrase: 'Quero falar com o médico' },
      { label: 'Enfermeira', emoji: '👩‍⚕️', phrase: 'Preciso da enfermeira' },
      { label: 'Família', emoji: '👨‍👩‍👧', phrase: 'Quero ver minha família' },
      { label: 'Sozinho', emoji: '🧘', phrase: 'Preciso de um momento sozinho' },
    ],
  },
]
